services:
  - type: web
    name: quantumbuild
    env: node
    region: singapore
    plan: free
    buildCommand: cd backend && npm install
    startCommand: node backend/server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_FROM
        value: noreply@quantumbuild.com
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://quantum-build-frontend.vercel.app
      - key: DASHBOARD_URL
        value: https://quantum-build-dashboard.vercel.app
